services:
  mongodb:
    # image: docker.m.daocloud.io/mongodb/mongodb-community-server:latest
    image: mongodb/mongodb-community-server:latest
    container_name: litflix-mongodb
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb_data:/data/db
    networks:
      - litflix-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: ohaiya/litflix-svr:latest
    container_name: litflix-svr
    environment:
      - MONGODB_URI=mongodb://root:root@litflix-mongodb:27017/lit-flix?authSource=admin
      - JWT_SECRET=1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - PORT=3001
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    volumes:
      - litflix_storage:/app/uploads
    networks:
      - litflix-network

  ui:
    build:
      context: .
      dockerfile: Dockerfile
    image: ohaiya/litflix-ui:latest
    container_name: litflix-ui
    # environment:
    #   - NGINX_PORT=5123
    #   - SERVER_IP=server
    #   - SERVER_PORT=3001
    ports:
      - "5123:5123"
    depends_on:
      - server
    networks:
      - litflix-network

networks:
  litflix-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  litflix_storage:
    driver: local